///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String icons404 = 'assets/icons/404.svg';
  static const String iconsError = 'assets/icons/error.svg';
  static const String iconsPaperPlane = 'assets/icons/paper_plane.svg';
}
